config/routes.rb
Mellowgasm::Application.routes.draw do
  root :to => 'home#landing'
  resources :users, :only => [:index, :new, :create, :show]
  resources :friends

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/home' => 'home#index'

  post '/new_map' => 'home#new_map'

  get 'venues/:id' => 'venues#ven_show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @friend = Friend.new
    @friends = Friend.all
    @location = @auth.locations.first
    @venues = @location.venues
    @top_picks = Venue.top_picks
    # @venues = @location.venues
  end

  def new_map

    @motivation = Motivation.where(:desire => params["motivations"]["name"]).first

    @location = Location.find_or_create_by_address(params['serchmap'])
    if !@auth.locations.include? @location
      @auth.locations << @location
    end
    if !@location.venues.where(:motivation_id => @motivation.id).present?
        Venue.make_venues(@location, @motivation)
      end
      @venues = @location.venues.where(:motivation_id => @motivation.id)
      @top_picks = Venue.top_picks
  end
end



# access_token = 4LHKYT3P4GINK5FYWSOLXPIZSKLBZ3NV2IWCWJC5W2VTXCCF

#foursquare.venues.search(:ll => "40.714353,-74.005973")


#4bf58dd8d48988d116941735 bars
#4bf58dd8d48988d11f941735 nightclub



# nightlife = ["4d4b7105d754a06376d81259",
# "4bf58dd8d48988d117941735",
# "4bf58dd8d48988d11e941735",
# "4bf58dd8d48988d118941735",
# "4bf58dd8d48988d1d8941735",
# "4bf58dd8d48988d119941735",
# "4bf58dd8d48988d120941735",
# "4bf58dd8d48988d121941735",
# "4bf58dd8d48988d11f941735",
# "4bf58dd8d48988d11b941735",
# "4bf58dd8d48988d1d4941735",
# "4bf58dd8d48988d122941735"]

# q= client.search_venue(:ll => ' ')
# category_id = q["groups"].first["items"].first["categories"].first["id"]


# https://api.foursquare.com/v2/venues/search?ll=40.7,-74&limit=200&offset=200?client_id=BA3SVMI1K40ZXF2GWCDEDK2QCTTN1QZB3TESSXVRGBM4E1OW&client_secret=FZNQMIZK1TK1XFOBP3LI4M43VV4HJ50WK4XWQBIZHSNQ34YU


# q= client.search_venues(options = {:ll => '40.714353,-74.005973', :limit => 50, :intent => 'browse', :radius => 2000, :categoryId => nightlife[0]})


# "https://api.foursquare.com/v2/venues/4eefd4506d86d722df8fd52e/photos?client_id=BA3SVMI1K40ZXF2GWCDEDK2QCTTN1QZB3TESSXVRGBM4E1OW&client_secret=FZNQMIZK1TK1XFOBP3LI4M43VV4HJ50WK4XWQBIZHSNQ34YU"

#picture= https://irs0.4sqi.net/img/user/100x100/blank_boy.png


#so we have our models.

#user provides his address => That becomes a location (with a latitude and longitude, and of course address)

#Location feeds into the query. Motivation (which has categoryId) also feeds into the Query. that query gets the list of venues.
#what do we do with those venues? We get a list of 50 results or so. Does that mean we populate our database with 50 venues or so ? Or would that increase the loading time too much? If so, then we might wanna limit it to 15 venues to create that amount of objects around. Those objects are saved as venues.

#These venues that are saved have addreses lat and lng. they aso have name.
#venue goes into photos, and we get photos from that..



# "https://api.foursquare.com/v2/venues/#{a}/photos?client_id=BA3SVMI1K40ZXF2GWCDEDK2QCTTN1QZB3TESSXVRGBM4E1OW&client_secret=FZNQMIZK1TK1XFOBP3LI4M43VV4HJ50WK4XWQBIZHSNQ34YU"

app/views/home/_map.html.haml
%script
  = "display_map(#{@location.latitude}, #{@location.longitude}, 13);"
  - @venues.each do |v|
    = "add_marker(#{v.latitude}, #{v.longitude}, 'Title', '#{v.id}', '#{v.name.gsub("'","")}', '#{v.distance}', '#{v.location.address}', '#{v.address}', '#{v.crossStreet}');"

app/views/home/_newmap.html.haml
%script
  = "display_map(#{ @location.latitude}, #{@location.longitude}, 13);"
%script
  var heatMapData = [
  {location: new google.maps.LatLng(40.69, -73.95), weight: 10},
  {location: new google.maps.LatLng(40.69, -73.95002), weight: 7},
  {location: new google.maps.LatLng(40.69, -73.95004), weight: 4},
  {location: new google.maps.LatLng(40.69, -73.95006), weight: 1},
  / new google.maps.LatLng(40.69, -73.95),
  / {location: new google.maps.LatLng(40.69, -73.950002), weight: 10},
  / {location: new google.maps.LatLng(40.69, -73.953), weight: 10},
  {location: new google.maps.LatLng(37.782, -122.439), weight: 2},
  new google.maps.LatLng(37.782, -122.437),
  {location: new google.maps.LatLng(37.782, -122.435), weight: 0.5},
  {location: new google.maps.LatLng(37.785, -122.447), weight: 3},
  {location: new google.maps.LatLng(37.785, -122.445), weight: 2},
  new google.maps.LatLng(37.785, -122.443),
  {location: new google.maps.LatLng(37.785, -122.441), weight: 0.5},
  new google.maps.LatLng(37.785, -122.439),
  {location: new google.maps.LatLng(37.785, -122.437), weight: 2},
  {location: new google.maps.LatLng(37.785, -122.435), weight: 3}];
  var heatmap = new google.maps.visualization.HeatmapLayer({data: heatMapData});
  heatmap.setMap(map);
%script
  add_marker(40.69, -73.95, 'yo');
  #markers
    - @venues.each do |v|
      %script
        = "add_marker(#{v.latitude}, #{v.longitude});"

app/views/home/_show.html.haml
%h2.title=@venue.name
-@photos.each do |photo|
  =image_tag(photo.url, :style => "height: 100px; width: 100px; float: left;")
%h5#sorry_sm{:style => 'clear:both;'}= "@#{@venue.twitter}" if @venue.twitter.present?
%h6#sorry_sm{:style => 'clear:both;'}= "+1#{@venue.phone}" if @venue.phone.present?
/ %h5= link_to("Visit #{@venue.name}", url => "#{@venue.url}") if @venue.url.present?
- if @venue.ratio > 0.0
  %h3#gender{:style => 'clear:both;'}="#{(@venue.ratio * 100).to_i}% Girls, #{(100 - (@venue.ratio * 100)).to_i}% Guys. Foursquare rating: #{(@venue.foursquare_rating.round(2) * 100).to_i}%"
-else
  %h3#gender{:style => 'clear:both;'}="#{(@venue.foursquare_rating.round(2) * 100).to_i}% foursquare rating"

-if !@photos.present?
  %h5= "Sorry, foursquare hasn't supplied much info on #{@venue.name}. Why don't you go out there and find out ;)"

app/views/home/_venue_list.html.haml
%h3.title MellowPicks
%ol
  -@top_picks.each do |top|
    %li= top

app/views/home/index.html.haml
= form_tag '/new_map', :remote => true do
  = text_field_tag "serchmap", nil, :autofocus => true
  = select(:motivations, :name, options_for_select([["All Nightlife"], ["All Bars"], ["Dive Bars"], ["Gay Bars"], ["Lounges"], ["The Club Scene"]]))
  = submit_tag 'Cruise Joints', :class => 'test_btn', :id => 'submit_button'
.row
  .large-4.columns
    %h3#header_cruise
    #map_daddy
      #map_canvas
        = render 'map'
.row
  .large-4.columns
    #top_venues
      =render 'venue_list'
    .table
      .tr
      .td
.row
  .five.columns
    %h3#header_cruise New Friend
    #friend_form
      = render 'friends/form'
.row
  .seven.columns
    #friends
      %table
      - @friends.each do |f|
        %tr
          %td= f.name
          %td= f.phone
#venue_show.reveal-modal
  #TheLowDown
  #donut-example
  %a.close-reveal-modal.fuck{:style => "color: #000044; font-style: bold;"} x

app/views/home/landing.html.haml
%br
%br

.landingmessage
  <em>Mellowgasm</em> gives you crucial hints on where to find your new match, regardless of your tastes.
.landingmessagelogin
  / ="Log in up top." if !@auth.present?
  =link_to("Log on in!", login_path, :remote => true, :id => 'login') if !@auth.present?
  / =link_to("Scope it out >", home_path) if @auth.present?
  =link_to("Scope it out >", home_path) if @auth.present?

app/views/home/new_map.js.erb
$('#map_canvas').empty().append('<%=j render(:partial => 'map') %>');


$('#top_venues').empty().append('<%=j render(:partial => 'venue_list') %>');